import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Layout/Header';
import { Footer } from '@/components/Layout/Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hub Tecnologia & Inovação',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
